openapi: 3.0.0
info:
  title: APIv1
  version: 1.0.0
  description: APIv1 for todo-app rails
servers:
  - url: http://127.0.0.1:3000/

paths:
  /api/v1/todos:
    get:
      tags: ["todo"]
      operationId: apiV1GetTodos
      summary: 全てのTodoを取得する
      responses:
        "200":
          description: getTodos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseTodos"
    post:
      tags: ["todo"]
      operationId: apiV1PostTodos
      summary: Todoを作成する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/postRequestTodo"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseTodo"
        # "400":
        #   description: Bad Request
        # "403":
        #   description: Forbidden
        # "422":
        #   description: Unprocessable Entity
        #   content:
        #     application/json:
        #       schema:
        #         type: object
        #         properties:
        #           error:
        #             type: array
        #             items:
        #               type: string
        #         additionalProperties: false
  /api/v1/todos/{id}:
    get:
      tags: ["todo"]
      operationId: apiV1GetTodoById
      summary: IDでTodoを取得する
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseTodo"
        # "404":
        #   description: Not Found
        #   content:
        #     application/json:
        #       schema:
        #         type: object
        #         properties:
        #           error:
        #             type: string
        #         additionalProperties: false
    put:
      tags: ["todo"]
      operationId: apiV1PutTodos
      summary: Todoを更新する
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/putRequestTodo"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseTodo"
        # "400":
        #   description: Bad Request
        # "403":
        #   description: Forbidden
        # "404":
        #   description: Not Found
        #   content:
        #     application/json:
        #       schema:
        #         type: object
        #         properties:
        #           error:
        #             type: string
        # "422":
        #   description: Unprocessable Entity
        #   content:
        #     application/json:
        #       schema:
        #         type: object
        #         properties:
        #           error:
        #             type: array
        #             items:
        #               type: string
        #         additionalProperties: false
    delete:
      tags: ["todo"]
      operationId: apiV1DeleteTodoById
      summary: IDでTodoを削除する
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseTodo"
        # "404":
        #   description: Not Found
        #   content:
        #     application/json:
        #       schema:
        #         type: object
        #         properties:
        #           error:
        #             type: string
        #         additionalProperties: false
components:
  schemas:
    postRequestTodo:
      type: object
      properties:
        todo:
          type: object
          properties:
            title:
              type: string
              example: "積読を減らす"
            description:
              type: string
              example: "技術書を1冊読み終える"
          required:
            - title
      required:
        - todo
      additionalProperties: false
    putRequestTodo:
      type: object
      properties:
        todo:
          type: object
          properties:
            id:
              type: integer
              format: int64
              example: 1
            title:
              type: string
              example: "積読を減らす"
            description:
              type: string
              example: "技術書を1冊読み終える"
          required:
            - id
            - title
      required:
        - todo
      additionalProperties: false
    responseTodos:
      type: object
      properties:
        todos:
          type: array
          items:
            $ref: "#/components/schemas/todo"
      required:
        - todos
      additionalProperties: false
    responseTodo:
      type: object
      properties:
        todo:
          $ref: "#/components/schemas/todo"
      required:
        - todo
      additionalProperties: false
    todo:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: "積読を減らす"
        description:
          type: string
          example: "技術書を1冊読み終える"
          nullable: true
        done:
          type: boolean
          default: false
        created_at:
          type: string
          format: date-time
          example: "2021-01-01T00:00:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2021-01-01T00:00:00Z"
      required:
        - id
        - title
        - done
        - created_at
        - updated_at
      additionalProperties: false
