openapi: 3.0.0
info:
  title: APIv1
  version: 1.0.0
  description: APIv1 for todo-app rails
servers:
  - url: http://127.0.0.1:3000/

paths:
  /api/v1/todos:
    get:
      tags: ["todo"]
      operationId: apiV1GetTodos
      summary: 全てのTodoを取得する
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  todos:
                    type: array
                    items:
                      $ref: "#/components/schemas/Todo"
components:
  schemas:
    Todo:
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: "積読を減らす"
        done:
          type: boolean
          default: false
      required:
        - id
        - title
        - done
