openapi: 3.0.0
info:
  title: APIv1
  version: 1.0.0
  description: APIv1 for todo-app rails
servers:
  - url: http://127.0.0.1:3000/

paths:
  /api/v1/todos:
    get:
      tags: ["todo"]
      operationId: apiV1GetTodos
      summary: 全てのTodoを取得する
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  todos:
                    type: array
                    items:
                      $ref: "#/components/schemas/Todo"
    post:
      tags: ["todo"]
      operationId: apiV1PostTodos
      summary: Todoを作成する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "積読を減らす"
                description:
                  type: string
                  example: "技術書を1冊読み終える"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: array
                    items:
                      type: string
  /api/v1/todos/{id}:
    get:
      tags: ["todo"]
      operationId: apiV1GetTodoById
      summary: IDでTodoを取得する
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    Todo:
      properties:
        id:
          type: integer
          format: int64
          example: 1
        title:
          type: string
          example: "積読を減らす"
        description:
          type: string
          example: "技術書を1冊読み終える"
        done:
          type: boolean
          default: false
      required:
        - id
        - title
        - done
