/* tslint:disable */
/* eslint-disable */
/**
 * APIv1
 * APIv1 for todo-app rails
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface ApiV1GetTodoById404Response
 */
export interface ApiV1GetTodoById404Response {
    /**
     * 
     * @type {string}
     * @memberof ApiV1GetTodoById404Response
     */
    'error'?: string;
}
/**
 * 
 * @export
 * @interface ApiV1GetTodos200Response
 */
export interface ApiV1GetTodos200Response {
    /**
     * 
     * @type {Array<Todo>}
     * @memberof ApiV1GetTodos200Response
     */
    'todos'?: Array<Todo>;
}
/**
 * 
 * @export
 * @interface ApiV1PostTodos422Response
 */
export interface ApiV1PostTodos422Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1PostTodos422Response
     */
    'error'?: Array<string>;
}
/**
 * 
 * @export
 * @interface ApiV1PostTodosRequest
 */
export interface ApiV1PostTodosRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiV1PostTodosRequest
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1PostTodosRequest
     */
    'description'?: string;
}
/**
 * 
 * @export
 * @interface Todo
 */
export interface Todo {
    /**
     * 
     * @type {number}
     * @memberof Todo
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof Todo
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof Todo
     */
    'description'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Todo
     */
    'done': boolean;
}

/**
 * TodoApi - axios parameter creator
 * @export
 */
export const TodoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary IDでTodoを削除する
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1DeleteTodoById: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiV1DeleteTodoById', 'id', id)
            const localVarPath = `/api/v1/todos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary IDでTodoを取得する
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1GetTodoById: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiV1GetTodoById', 'id', id)
            const localVarPath = `/api/v1/todos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 全てのTodoを取得する
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1GetTodos: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/todos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Todoを作成する
         * @param {ApiV1PostTodosRequest} apiV1PostTodosRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PostTodos: async (apiV1PostTodosRequest: ApiV1PostTodosRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiV1PostTodosRequest' is not null or undefined
            assertParamExists('apiV1PostTodos', 'apiV1PostTodosRequest', apiV1PostTodosRequest)
            const localVarPath = `/api/v1/todos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiV1PostTodosRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary IDでTodoを更新する
         * @param {number} id 
         * @param {Todo} todo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PutTodoById: async (id: number, todo: Todo, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiV1PutTodoById', 'id', id)
            // verify required parameter 'todo' is not null or undefined
            assertParamExists('apiV1PutTodoById', 'todo', todo)
            const localVarPath = `/api/v1/todos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(todo, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TodoApi - functional programming interface
 * @export
 */
export const TodoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TodoApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary IDでTodoを削除する
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1DeleteTodoById(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Todo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1DeleteTodoById(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary IDでTodoを取得する
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1GetTodoById(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Todo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1GetTodoById(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 全てのTodoを取得する
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1GetTodos(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiV1GetTodos200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1GetTodos(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Todoを作成する
         * @param {ApiV1PostTodosRequest} apiV1PostTodosRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1PostTodos(apiV1PostTodosRequest: ApiV1PostTodosRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Todo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1PostTodos(apiV1PostTodosRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary IDでTodoを更新する
         * @param {number} id 
         * @param {Todo} todo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1PutTodoById(id: number, todo: Todo, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Todo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1PutTodoById(id, todo, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TodoApi - factory interface
 * @export
 */
export const TodoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TodoApiFp(configuration)
    return {
        /**
         * 
         * @summary IDでTodoを削除する
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1DeleteTodoById(id: number, options?: any): AxiosPromise<Todo> {
            return localVarFp.apiV1DeleteTodoById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary IDでTodoを取得する
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1GetTodoById(id: number, options?: any): AxiosPromise<Todo> {
            return localVarFp.apiV1GetTodoById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 全てのTodoを取得する
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1GetTodos(options?: any): AxiosPromise<ApiV1GetTodos200Response> {
            return localVarFp.apiV1GetTodos(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Todoを作成する
         * @param {ApiV1PostTodosRequest} apiV1PostTodosRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PostTodos(apiV1PostTodosRequest: ApiV1PostTodosRequest, options?: any): AxiosPromise<Todo> {
            return localVarFp.apiV1PostTodos(apiV1PostTodosRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary IDでTodoを更新する
         * @param {number} id 
         * @param {Todo} todo 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1PutTodoById(id: number, todo: Todo, options?: any): AxiosPromise<Todo> {
            return localVarFp.apiV1PutTodoById(id, todo, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TodoApi - object-oriented interface
 * @export
 * @class TodoApi
 * @extends {BaseAPI}
 */
export class TodoApi extends BaseAPI {
    /**
     * 
     * @summary IDでTodoを削除する
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodoApi
     */
    public apiV1DeleteTodoById(id: number, options?: AxiosRequestConfig) {
        return TodoApiFp(this.configuration).apiV1DeleteTodoById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary IDでTodoを取得する
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodoApi
     */
    public apiV1GetTodoById(id: number, options?: AxiosRequestConfig) {
        return TodoApiFp(this.configuration).apiV1GetTodoById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 全てのTodoを取得する
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodoApi
     */
    public apiV1GetTodos(options?: AxiosRequestConfig) {
        return TodoApiFp(this.configuration).apiV1GetTodos(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Todoを作成する
     * @param {ApiV1PostTodosRequest} apiV1PostTodosRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodoApi
     */
    public apiV1PostTodos(apiV1PostTodosRequest: ApiV1PostTodosRequest, options?: AxiosRequestConfig) {
        return TodoApiFp(this.configuration).apiV1PostTodos(apiV1PostTodosRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary IDでTodoを更新する
     * @param {number} id 
     * @param {Todo} todo 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodoApi
     */
    public apiV1PutTodoById(id: number, todo: Todo, options?: AxiosRequestConfig) {
        return TodoApiFp(this.configuration).apiV1PutTodoById(id, todo, options).then((request) => request(this.axios, this.basePath));
    }
}


